# Generated by Django 3.0.8 on 2020-07-20 10:36

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('main_text', markdownx.models.MarkdownxField(verbose_name='本文')),
            ],
        ),
    ]
